* add gettext to (build-) dependencies * add gettext support and german language file * changed Xdialog to ssft

diff --git a/capi-isdnconf b/capi-isdnconf
--- a/capi-isdnconf
+++ b/capi-isdnconf
@@ -1,64 +1,81 @@
 #!/bin/bash
 
-[ "$UID" -ne 0 ] && exec su-me "$0" "$@"
+# we need gettext (is loaded in ssft.sh or cloned...)
+if [ -f /usr/bin/gettext.sh ]; then
+	. /usr/bin/gettext.sh || exit 1
+else
+	exit 1
+fi
+#---------------------------------------------------------------------
+# we need root rights
+#---------------------------------------------------------------------
+SU_ME=$(type -p su-me)  || SU_ME="/usr/bin/su-me"
+if [ "$UID" -ne 0 ]; then
+	[ -x "$SU_ME" ] && exec "$SU_ME" "$0" "$@"
 
-XDIALOG_HIGH_DIALOG_COMPAT=1
-export XDIALOG_HIGH_DIALOG_COMPAT
-LANG=C
-export LANG
+	printf "$(gettext "Error: You must be root to run this script!")\n"
+	exit 1
+fi
 
-DIALOG=dialog
-[ -n "$DISPLAY" ] && [ -x /usr/bin/Xdialog ] && DIALOG="Xdialog"
+TEXTDOMAIN="capi-isdnconf"
+export TEXTDOMAIN
+TEXTDOMAINDIR=/usr/share/locale
+export TEXTDOMAINDIR
+
+
+SSFTSH="$(which ssft.sh)"			|| SSFTSH="/usr/bin/ssft.sh"
+# initialize ssft
+. "$SSFTSH"
+[ -n "$SSFT_FRONTEND" ] ||  SSFT_FRONTEND="$(ssft_choose_frontend)"
+
 
 function inputbox {
 	# inputbox title text width [init]
-	$DIALOG --stdout --title "$1" --inputbox "\n$2\n\n" 10 $3 "$4"
+	SSFT_DEFAULT="$3"
+	ssft_read_string "$1" "$2"
+	unset SSFT_DEFAULT
+	[ -n "$SSFT_RESULT" ] && printf "$SSFT_RESULT\n"
 }
 
 function msgbox {
 	# msgbox title text width
-	$DIALOG --title "$1" --msgbox "\n$2\n" $((${#2}/($3-4)+7)) $3
+	ssft_display_message "$1" "$2"
 }
 
 function yesno {
 	# yesno title text width
-	$DIALOG --title "$1" --yesno "\n$2\n" $((${#2}/($3-4)+7)) $3
-	echo "$?"
+	ssft_yesno "$1" "$2" && printf "0\n" || printf "1\n"
 }
 
-TITLE="CAPI Configuration for ISDN"
-PROVIDER="$(inputbox "$TITLE" "ISDN provider" 55 capi-isdn)"
-[ "$?" != 0 ] && exit 1
+#main
+TITLE="$(gettext "CAPI Configuration for ISDN")"
+PROVIDER="$(inputbox "$TITLE" "$(gettext "ISDN provider")" capi-isdn)"
 if [ "$PROVIDER" = "" ]; then
-	msgbox "$TITLE" "Error: bad provider name" 55
+	msgbox "$TITLE" "$(gettext "Error: bad provider name")"
 	exit 10
 fi
 
-NUMBER="$(inputbox "$TITLE" "ISDN number" 55)"
-[ "$?" != 0 ] && exit 2
+NUMBER="$(inputbox "$TITLE" "$(gettext "ISDN number")")"
 if [ "$NUMBER" = "" ]; then
-	msgbox "$TITLE" "Error: bad number" 55
+	msgbox "$TITLE" "$(gettext "Error: bad number")"
 	exit 20
 fi
 
-USERNAME="$(inputbox "$TITLE" "ISDN username" 55)"
-[ "$?" != 0 ] && exit 3
+USERNAME="$(inputbox "$TITLE" "$(gettext "ISDN username")")"
 if [ "$USERNAME" = "" ]; then
-	msgbox "$TITLE" "Error: bad username" 55
+	msgbox "$TITLE" "$(gettext "Error: bad username")"
 	exit 30
 fi
 
-PASSWORD="$(inputbox "$TITLE" "ISDN password" 55)"
-[ "$?" != 0 ] && exit 4
+PASSWORD="$(inputbox "$TITLE" "$(gettext "ISDN password")")"
 if [ "$PASSWORD" = "" ]; then
-	msgbox "$TITLE" "Error: bad password" 55
+	msgbox "$TITLE" "$(gettext "Error: bad password")"
 	exit 40
 fi
 
-MSN="$(inputbox "$TITLE" "ISDN outgoing MSN" 55)"
-[ "$?" != 0 ] && exit 5
+MSN="$(inputbox "$TITLE" "$(gettext "ISDN outgoing MSN")")"
 if [ "$MSN" = "" ]; then
-	msgbox "$TITLE" "Error: bad MSN" 55
+	msgbox "$TITLE" "$(gettext "Error: bad MSN")"
 	exit 50
 fi
 
@@ -98,7 +115,7 @@ if [ ! -e /etc/debian_version ]; then
 	ln -s ppp/resolv.conf /etc/resolv.conf
 fi
 
-CONNECT=$(yesno "$TITLE" "Connect now?" 50)
+CONNECT=$(yesno "$TITLE" "$(gettext "Connect now?")")
 [ "$CONNECT" = "1" ] && exit 50
 
 PPPD=/usr/sbin/pppd
